
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: controller-role
rules:
- apiGroups:
  - tg.my.domain
  resources:
  - learns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tg.my.domain
  resources:
  - learns/finalizers
  verbs:
  - update
- apiGroups:
  - tg.my.domain
  resources:
  - learns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - create
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - list
  - create
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create